service: watchcircle-app-ws
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:custom.tableName}
    STAGE: ${self:provider.stage}
    WS_JWT_SECRET: ${env:WS_JWT_SECRET, ''}
    SESSION_JWT_SECRET: ${env:SESSION_JWT_SECRET, ''}
    DYNAMO_ENDPOINT: ${env:DYNAMO_ENDPOINT, ''}
    WS_MANAGEMENT_ENDPOINT: ${env:WS_MANAGEMENT_ENDPOINT, ''}

custom:
  tableName: WatchCircle-${self:provider.stage}

functions:
  connect:
    handler: src/index.connectHandler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/index.disconnectHandler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: src/index.defaultHandler
    events:
      - websocket:
          route: $default

plugins:
  - serverless-esbuild

package:
  individually: true
